# Generated by Django 3.2 on 2021-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20210604_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('P', 'Parent'), ('US', 'Unsubscribed')], default='US', max_length=2),
        ),
    ]
