# Generated by Django 3.2 on 2021-08-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Keyword Matching', 'Keyword Matching'), ('Notes', 'Notes')], max_length=20),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('format', models.CharField(choices=[('Video', 'Video'), ('Word', 'Word')], max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.type'),
        ),
    ]
