# Generated by Django 3.2 on 2021-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210804_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
