# Generated by Django 3.2 on 2021-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.CharField(default='link', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.CharField(default='thumbnail', max_length=50),
            preserve_default=False,
        ),
    ]
