# Generated by Django 3.2 on 2021-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210804_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('Short Answer Quiz', 'Short Answer Quiz'), ('Keyword Matching', 'Keyword Matching'), ('Notes', 'Notes'), ('Practice Drills', 'Practice Drills')], max_length=20),
        ),
    ]
