# Generated by Django 3.2 on 2021-08-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='lesson',
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Short Answer Quiz', 'Short Answer Quiz'), ('Keyword Matching', 'Keyword Matching'), ('Notes', 'Notes'), ('Practice Drills', 'Practice Drills')], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
