# Generated by Django 3.2 on 2021-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210806_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(choices=[('video', 'Video'), ('PDF', 'PDF'), ('Word', 'Word')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('SAQ', 'Short Answer Quiz'), ('KWM', 'Keyword Matching'), ('N', 'Notes'), ('PD', 'Practice Drills')], max_length=3),
        ),
    ]
