# Generated by Django 3.2 on 2021-08-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_resource_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='thumbnail',
        ),
    ]
