# Generated by Django 3.2 on 2021-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_remove_resource_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(choices=[('video', 'Video'), ('PDF', 'PDF'), ('Word', 'Word')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.CharField(choices=[('KC', 'Key concepts in chemistry'), ('SLG&M', 'States of matter and mixtures'), ('CC', 'Chemical changes'), ('EM&E', 'Extracting metals and equilibria'), ('SC1', 'Separate chemistry 1'), ('PT', 'Groups in the periodic table'), ('ROR', 'Rates of reaction and energy changes'), ('F&ES', 'Fuels and Earth science'), ('SC2', 'Separate chemistry 2')], max_length=5),
        ),
    ]
