# Generated by Django 3.2 on 2021-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210807_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='to be changed', max_length=200),
            preserve_default=False,
        ),
    ]
